import streamlit as st

def navigation_menu():
    # Show a navigation menu for authenticated users
    st.sidebar.title("Course Content")
    st.sidebar.page_link("streamlit_app.py", label="Home")
    st.sidebar.markdown("Ch. 1: Linear Regression")
    st.sidebar.page_link("pages/chapter_1_linear_regression.py", label="Content")
    st.sidebar.page_link("pages/tutorial_1_linear_regression.py", label="Tutorial")
    st.sidebar.markdown("Ch. 2: Logistic Regression")
    st.sidebar.page_link("pages/chapter_2_logistic_regression.py", label="Content")
    st.sidebar.page_link("pages/tutorial_2_logistic_regression.py", label="Tutorial")
    st.sidebar.markdown("Ch. 3: Clustering")  # Changed from "Neural Networks"
    st.sidebar.page_link("pages/chapter_3_clustering.py", label="Content")
    st.sidebar.page_link("pages/tutorial_3_clustering_kmeans.py", label="Tutorial: K-Means")
    st.sidebar.page_link("pages/tutorial_3_clustering_gmm.py", label="Tutorial: GMM")
    st.sidebar.markdown("Ch. 4: PCA")
    st.sidebar.page_link("pages/chapter_4_pca.py", label="Content")
    st.sidebar.page_link("pages/tutorial_4_pca.py", label="Tutorial")
    st.sidebar.markdown("Ch. 5: Neural Network Supervised")
    st.sidebar.page_link("pages/chapter_5_neural_network_supervised.py", label="Content")
    st.sidebar.page_link("pages/tutorial_5_multilayer_perceptron.py", label="Tutorial: MLP")
    st.sidebar.page_link("pages/tutorial_5_pytorch.py", label="Tutorial: PyTorch")
    st.sidebar.markdown("Ch. 6: Neural Network Unsupervised")
    st.sidebar.page_link("pages/chapter_6_neural_network_unsupervised.py", label="Content")
    st.sidebar.page_link("pages/tutorial_6_autoencoder.py", label="Tutorial: Autoencoder")
    st.sidebar.page_link("pages/tutorial_6_mixed_density_network.py", label="Tutorial: MDN")
    st.sidebar.markdown("Ch. 7: Gaussian Process Regression")
    st.sidebar.page_link("pages/chapter_7_gaussian_process_regression.py", label="Content")
    st.sidebar.page_link("pages/tutorial_7_gaussian_process_regression.py", label="Tutorial")
    st.sidebar.markdown("Ch. 8: Gaussian Process Classification")
    st.sidebar.page_link("pages/chapter_8_gaussian_process_classification.py", label="Content")
    st.sidebar.page_link("pages/tutorial_8_gaussian_process_classification.py", label="Tutorial")
    st.sidebar.markdown("Ch. 9: Sampling")
    st.sidebar.page_link("pages/chapter_9_sampling.py", label="Content")
    st.sidebar.page_link("pages/tutorial_9_sampling.py", label="Tutorial")
    st.sidebar.markdown("Ch. 10: Markov Chain Monte Carlo")
    st.sidebar.page_link("pages/chapter_10_markov_chain_monte_carlo.py", label="Content")
    st.sidebar.page_link("pages/tutorial_10_markov_chain_monte_carlo.py", label="Tutorial")
